### ISSUE TITLE
Suggestion: Why not pull the entire search from pornmd.com?

### ISSUE THREAD

**Issue by brian-tx** [moedje/plugin.video.hubgay#1]
Hello,

I came across this project and noticed you're pulling searches from several sites simultaniously. While that's not a problem, you may want to consider doing the search directly from pornmd.com, as almost all of the sites you are searching are owned by the parent company of Pornhub, and PornMD is the site they built to aggregate searches from all of their other sites. Just a suggestion :)

**Comment by moedje** [comment]
Yeah I am aware of pornmd but at the time of writing the pornhub API I use to query didn’t have an API for PornMD and unlike other addons that scrape the websites this hooks directly into the database feeds to get JSON objects back which I then convert into valid Kodi ListElements. I will have to check back at the HUB Affiliates to see if the API has been updated at all.
